### ISSUE TITLE
cannot download file uploaded to MetaDisk

### ISSUE THREAD

**Issue by heunland** [StorjOld/MetaDisk#68] opened 2014-09-10 13:42 UTC
I ran across an error on node 1 of MetaDisk: I have uploaded a file to node 1 here: http://node1.metadisk.org/api/download/d0c4429be4bf6321874f7680b3106c4371a6bb22a8eedc2abe9bbd7f9d4b06f2?key=53b29acb15a04811f520e5b2ef6fa89f5fb6b26c079dd6b93c520a9b704d3e6d&token=saAToOJZ8AVCTYgM
A storjtalk user I shared the link with tried to download it and says the link is dead. When I try to download it myself, it gives this error: "Whoops, we were unable to download your file because of an insufficient balance". I guess its complaining that I don´t have enough SJCX available for the download? Are we already charging for downloads? My other files download without problem. Also I uploaded the same file again on another machine and again was unable to download it. Error: Internal Error

**Comment by EmergentBehavior** [comment] 2014-09-10 18:56
Shouldn't be happening on node1. This is a bug.

Duplicate of https://github.com/Storj/web-core/issues/13.

**Closed as completed by EmergentBehavior** 2014-09-10 18:56 UTC
Labels: duplicate issue
